version: '3.9'
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
  
  api:
    build: .
    ports:
      - 8000:5000
    volumes: 
      - .:/usr/src/app
    environment:
      NODE_ENV: development
      PORT: 5000
      SOCKET_PORT: 3000
      MONGO_URI: mongodb://mongo_db:27017
      JWT_SECRET: TOKENSECRET101
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}